apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: singularity-data
  namespace: singularity
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
